### ISSUE TITLE
Doubt with ZNC + IRC Scraper

### ISSUE THREAD

**Issue by PREngineer** [nZEDb/nZEDb_Misc#4]
Hi!

I've followed the guide to set up ZNC + IRC Scraper but it is not very clear.

I installed it but when I run TMUX, I only see the message: "Pane is Dead" in the 3rd Tab.

First I was getting a (111) error which I think was related to SSL in the connection to ZNC.

Then I was getting an error (0) which I fixed by using the right port, 6664.

Now I only get the Dead Pane message.  Nothing ever shows up.

Could you please review the instructions an clear them up a bit?

--------

Findings:

Instructions say to use port 6697 for the connection.  I tried it using KiwiIRC and it couldn't connect.  The correct port is 6667.

Also, the irc.synirc.net server DOES NOT use SSL.

When connecting through ZNC, Tab3 never shows any input [Added Pre] or [Updated Pre].
When connecting directly from IRC Scraper it DOES show the inputs, how come?

**Comment by DariusIII** [comment]
Have you followed this guide: https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Various/IRCScraper/Guide.md ?

**Comment by PREngineer** [comment]
Yes I did... Then I started messing around with settings and came up with the findings that I edited later into my comment.

I got it working directly from the IRC Channel however, if I use the ZNC it gets nothing.  Don't know why.

**Comment by DariusIII** [comment]
Is your ZNC setup correctly? You connect to the port ZNC uses, not one of the ports of synirc. Username is your ZNC user, pass is your ZNC pass. The real connection to the channel is set in ZNC.

**Comment by PREngineer** [comment]
Yes, I checked those issues.  I will attempt to reconfigure it again.  I'm suspecting that the SSL could be the problem was I did as the guide says but it doesn't use SSL.  I'll let you know tomorrow.  It is late here and I'm going to sleep now.

**Comment by PREngineer** [comment]
Got it working.  It was indeed a problem with the configuration.

1. Address 0.0.0.0 was not bound in the IRC Server even though I put it while creating the conf.
2. I made sure that SSL was DISABLED.
3. Went inside the Web Interface and re-checked the configuration.

I'm getting results now using ZNC.

**Comment by PREngineer** [comment]
I'm noticing that when connected through ZNC, IRC Scraper misses releases but when I connect directly I get them all.

Are any tweaks necessary?

**Comment by PREngineer** [comment]
If I add multiple channels to ZNC, does Irc Scraper uses all of them or do they have to be configured?

**Comment by PREngineer** [comment]
http://forums.nzedb.com/index.php?topic=2000.0

Just found this guide.  I think it could be helpful for anybody else who may face issues.
