### ISSUE TITLE
i love this script :)

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb_Misc#6]
@kevinlekiller any chance of updating it?  it truly helps me keep my many test and prod systems up to date :)

**Comment by kevinlekiller** [comment]
Hey Dil, which script?

**Comment by Wally73** [comment]
only script i see here is https://github.com/nZEDb/nZEDb_Misc/blob/master/Scripts/Linux/autobin.sh

**Comment by kevinlekiller** [comment]
Alright, what's wrong with it?

I quickly looked over, I think the unrar would fail currently since it picks up "5.30" as the version, since the HTML says <b>RAR 5.30 for Linux</b></a></td> but the URL is <td><a href="/rar/rarlinux-5.3.0.tar.gz">

**Comment by dilbaggins** [comment]
two items i was thinking. (sorry was out of pocket and couldnt respond quickly)

1) the update for the tools (i.e. the item you mentioned with unrar etc.
2) documentation,  so does this tool update the utilities in /bin as a default?  i just want to ensure i am pointing nzedb's utility paths on the admin page for instance. 

i just love this script :)

**Comment by kevinlekiller** [comment]
From what I can see in the script source, the default path is `~/bin` (`/home/dildbaggins/bin` for example), you can change this here: https://github.com/nZEDb/nZEDb_Misc/blob/master/Scripts/Linux/autobin.sh#L56

I'll see what I can do about the unrar issue.

**Comment by dilbaggins** [comment]
thx @kevinlekiller

**Comment by kevinlekiller** [comment]
No worries.
